kind: Service
apiVersion: v1
metadata:
  name: xmichalikl-openapi-ui
spec:
  selector:
    pod: xmichalikl-equipment-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081