apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmichalikl-equipment-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /xmichalikl-openapi
            - name: BASE_URL
              value: /xmichalikl-openapi-ui