apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: xmichalikl-equipment-ufe
spec:
  module-uri: http://xmichalikl-equipment-ufe.wac-hospital/build/equipment-ufe.esm.js
                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: xmichalikl-equipment-app    # element, ktorý bude vložený na stránku
      attributes:
      - name: api-base
        value: /xmichalikl-api
                                   
      path: xmichalikl-equipment-app      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Evidencia vybavenia nemocnice a ambulancií (xmichalikl)      # názov mikro aplikácie
      details: Evidencia a objednávanie vybavenia nemocnice a ambulancií, s prehľadom umiestnenia a životnosti jednotlivých položiek
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha2             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach